name: Deploy to Cloudflare Worker

on:
  push:
    branches: [main]
    paths-ignore:
      - '**.md'

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: contains(github.event.head_commit.message, 'push and deploy to prod')

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Debug - List files and check package.json
        run: |
          pwd
          ls -la
          cat package.json

      - name: Install dependencies
        run: bun install
        working-directory: .

      - name: Make deploy script executable
        run: chmod +x deploy.sh

      - name: Deploy to Cloudflare Worker
        run: ./deploy.sh prod
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          PROD_PALETTE_KV_ID: ${{ secrets.PROD_PALETTE_KV_ID }}
          PROD_PALETTE_KV_PREVIEW_ID: ${{ secrets.PROD_PALETTE_KV_PREVIEW_ID }}
          DEV_PALETTE_KV_ID: ${{ secrets.DEV_PALETTE_KV_ID }}
          SECRETS_STORE_ID: ${{ secrets.SECRETS_STORE_ID }}

      - name: Run post-deploy script
        run: node scripts/post-deploy.js
        env:
          DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}
          DISCORD_DEPLOYMENT_WEBHOOK_URL: ${{ secrets.DISCORD_DEPLOYMENT_WEBHOOK_URL }}
          DEPLOYMENT_VERSION: ${{ github.sha }}
          DEPLOYED_BY: 'GitHub Actions'
