name: Deploy to Cloudflare Worker

on:
  push:
    branches: [main]
    paths-ignore:
      - '**.md'

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: contains(github.event.head_commit.message, 'push and deploy to prod' || contains(github.event.head_commit.message, 'deploy to prod') || contains(github.event.head_commit.message, 'deploy to production') || contains(github.event.head_commit.message, 'push to prod') || contains(github.event.head_commit.message, 'push to production') || contains(github.event.head_commit.message, 'prod deploy') || contains(github.event.head_commit.message, 'production deploy'))

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Debug - List files and check package.json
        run: |
          pwd
          ls -la
          cat package.json

      - name: Install dependencies
        run: bun install
        working-directory: .

      - name: Deploy to Cloudflare Worker
        run: bun wrangler deploy
        working-directory: .
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}

      - name: Run post-deploy script
        run: node scripts/post-deploy.js
        env:
          DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}
          DISCORD_DEPLOYMENT_WEBHOOK_URL: ${{ secrets.DISCORD_DEPLOYMENT_WEBHOOK_URL }}
          DEPLOYMENT_VERSION: ${{ github.sha }}
          DEPLOYED_BY: 'GitHub Actions'
